name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"
  Deploy-Pages:
    runs-on: ubuntu-latest
    needs: Explore-GitHub-Actions  # Explore-Github-Actions must succeed for this job to run
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # This shows the page URL in the job details on Github
    steps:
    # The README recommends using this action in a separate job
      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v4
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source